### ISSUE TITLE
Generated CSS is inconsistent with Esri design guidelines, overflows on mobile, is not responsive

### ISSUE THREAD

**Issue by oest0004** [Esri/arcgis-js-cli#123]
Minor CSS changes make the default app more consistent with esri design guidelines and fixes overflow and other design issues in mobile screen sizes

## Expected Behavior
there should not be overflow in the default css on common mobile form factors. the following is the css with the proposed changes implemented.
![image](https://github.com/Esri/arcgis-js-cli/assets/43123950/b6204af1-3836-4dd2-9944-8acd47535d86)

## Actual Behavior
![image](https://github.com/Esri/arcgis-js-cli/assets/43123950/f9d4af6a-5140-42b2-a397-55fccfe832f4)

As displayed in the image, the css is not responsive in mobile form factors. spacing does not follow standard esri spacing intervals (15px base) and it requires additional work for a new app.

## Possible Fix
Using the following CSS in the [Template for the Vite App](https://github.com/Esri/arcgis-js-cli/blob/2962f7b354011e8329718cf260e3e726079a4cdc/templates/vite/app/src/style.css) can fix the issues.

```css
/*************************************************
  Custom ArcGIS Maps SDK for JavaScript theming.
*************************************************/
@import url("https://js.arcgis.com/4.25/esri/themes/light/main.css");

@import "./_variables.css";

/*************************************************
  Add application and widget styles.
*************************************************/

html {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
*, *:before, *:after {
  -webkit-box-sizing: inherit;
  -moz-box-sizing: inherit;
  box-sizing: inherit;
  }


html,
body {
  padding: 0;
  margin: 0;
  height: 100%;
  width: 100%;
  font-size: 14px;
}

.app {
  display: flex;
  flex-flow: column;
  width: 100%;
  height: 100%;
  padding: 0;
  margin: 0;
  overflow: hidden;
}

.app--header {
  display: flex;
  flex-flow: row;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  padding: 12px 15px;
  background-color: var(--main-bg-color);
  color: var(--font-color-white);
}

.app--header-title {
  font-size: 20px;
  font-weight: 500;
}

@media screen and (min-width: 880px) {
  .app--header-search.esri-search {
    width: 340px;
  }
}
@media screen and (min-width: 1280px) {
  .app--header-search.esri-search {
    width: 640px;
  }
}

.app--view {
  flex: 1;
  width: 100%;
}
```

### Summary of Changes
- added the css box sizing fix, which fixes the overflow on the search bar on 
- removed hardcoded header size, to better accomodate various app titles, maintain consistent spacing with the search bar 
- added padding using standard esri spacing intervals (15px)

## Context
it adds additional setup time to making an app using the cli tool
